# Generated by Django 3.1.4 on 2020-12-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('video_system', models.CharField(max_length=30)),
                ('ports', models.IntegerField(max_length=3)),
                ('connections', models.CharField(max_length=1000)),
            ],
        ),
    ]
