# Generated by Django 3.1.4 on 2020-12-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switchs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='device_type',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='switch',
            name='ports',
            field=models.IntegerField(),
        ),
    ]
