# Generated by Django 3.1.4 on 2020-12-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switchs', '0002_auto_20201217_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='image',
            field=models.ImageField(default='Nonde', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='ip_address',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
    ]
