# Generated by Django 3.1.4 on 2020-12-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switchs', '0003_auto_20201217_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
