# Generated by Django 3.1.4 on 2020-12-23 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('switchs', '0004_auto_20201217_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='switch',
            old_name='ports',
            new_name='quantity_ports',
        ),
        migrations.RemoveField(
            model_name='switch',
            name='connections',
        ),
        migrations.RemoveField(
            model_name='switch',
            name='video_system',
        ),
    ]
