# Generated by Django 3.1.4 on 2020-12-23 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('switchs', '0007_auto_20201223_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='port',
            old_name='device_ip_address',
            new_name='ip_address_on_port',
        ),
        migrations.AddField(
            model_name='port',
            name='this_port_belong_to_switch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='switchs.switch'),
        ),
    ]
