# Generated by Django 3.1.4 on 2020-12-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switchs', '0009_auto_20201223_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='number_port',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='switch',
            name='quantity_ports',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
