# Generated by Django 3.1.4 on 2020-12-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switchs', '0010_auto_20201223_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='note',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='switch',
            name='device_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='switch',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name='switch',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
