# Generated by Django 3.1.4 on 2020-12-23 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('switchs', '0012_auto_20201223_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='device_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='switchs.devicetype'),
        ),
    ]
