# Generated by Django 3.1.4 on 2021-01-20 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('switchs', '0016_auto_20201224_0116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='switch',
            old_name='device_type',
            new_name='device_model',
        ),
        migrations.AlterField(
            model_name='port',
            name='this_port_belong_to_switch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='switchs.switch'),
        ),
    ]
