# Generated by Django 3.1.4 on 2021-01-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switchs', '0017_auto_20210120_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='quantity_ports',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
