# Generated by Django 3.1.4 on 2021-01-21 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('switchs', '0020_auto_20210121_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='switch',
            old_name='quantity_ports',
            new_name='number_of_ports',
        ),
    ]
