# Generated by Django 3.1.4 on 2021-01-21 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('switchs', '0021_auto_20210121_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='switch',
            old_name='number_of_ports',
            new_name='numbers_of_ports',
        ),
    ]
